../../code/muda < test1.in > test1.out
../../code/muda < test2.in > test2.out
../../code/muda < test3.in > test3.out
../../code/muda < test4.in > test4.out
../../code/muda < test5.in > test5.out
../../code/muda < test6.in > test6.out
../../code/muda < test7.in > test7.out
../../code/muda < test8.in > test8.out
../../code/muda < test9.in > test9.out
../../code/muda < test10.in > test10.out
../../code/muda < test11.in > test11.out
../../code/muda < test12.in > test12.out
../../code/muda < test13.in > test13.out
../../code/muda < test14.in > test14.out
../../code/muda < test15.in > test15.out
../../code/muda < test16.in > test16.out
../../code/muda < test17.in > test17.out
../../code/muda < test18.in > test18.out
../../code/muda < test19.in > test19.out
../../code/muda < test20.in > test20.out
../../code/muda < test21.in > test21.out
../../code/muda < test22.in > test22.out
../../code/muda < test23.in > test23.out
../../code/muda < test24.in > test24.out
../../code/muda < test25.in > test25.out
../../code/muda < test26.in > test26.out
../../code/muda < test27.in > test27.out
../../code/muda < test28.in > test28.out
../../code/muda < test29.in > test29.out
../../code/muda < test30.in > test30.out
../../code/muda < test31.in > test31.out
../../code/muda < test32.in > test32.out
../../code/muda < test33.in > test33.out
../../code/muda < test34.in > test34.out
../../code/muda < test35.in > test35.out
../../code/muda < test36.in > test36.out
../../code/muda < test37.in > test37.out
../../code/muda < test38.in > test38.out
../../code/muda < test39.in > test39.out
../../code/muda < test40.in > test40.out
../../code/muda < test41.in > test41.out
../../code/muda < test42.in > test42.out
../../code/muda < test43.in > test43.out
../../code/muda < test44.in > test44.out
../../code/muda < test45.in > test45.out
../../code/muda < test46.in > test46.out
../../code/muda < test47.in > test47.out
../../code/muda < test48.in > test48.out
../../code/muda < test49.in > test49.out
../../code/muda < test50.in > test50.out
../../code/muda < test51.in > test51.out
../../code/muda < test52.in > test52.out
../../code/muda < test53.in > test53.out
../../code/muda < test54.in > test54.out
../../code/muda < test55.in > test55.out
../../code/muda < test56.in > test56.out
../../code/muda < test57.in > test57.out
../../code/muda < test58.in > test58.out
../../code/muda < test59.in > test59.out
../../code/muda < test60.in > test60.out
../../code/muda < test61.in > test61.out
../../code/muda < test62.in > test62.out
../../code/muda < test63.in > test63.out
../../code/muda < test64.in > test64.out
../../code/muda < test65.in > test65.out
../../code/muda < test66.in > test66.out
../../code/muda < test67.in > test67.out
../../code/muda < test68.in > test68.out
../../code/muda < test69.in > test69.out
find -iname "test*"  | xargs zip testes.zip
