# Generated by Django 2.2.6 on 2020-01-09 11:52

import contest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_contest_out_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='in_files',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='out_files',
        ),
        migrations.AddField(
            model_name='test',
            name='opt_file1',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=contest.models.get_tests_path),
        ),
        migrations.AddField(
            model_name='test',
            name='opt_file2',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=contest.models.get_tests_path),
        ),
    ]
